version: '3'
services:
  service1:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    # environment:
    # - MONGO_URI=mongodb://host.docker.internal:27017
    # - MONGO_URI=mongodb://mongo:27017
    # - MONGO_DB_NAME=claspMobileDB
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    # depends_on:
    #   - mongo

    # mongo:
    #   image: mongo
    #   restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: password
    # volumes:
    #   - mongo_data:/data/db
    # ports:
    #   - "27017:27017"

    # nginx:
    #   image: nginx
    #   volumes:
    #     - ./nginx.conf:/etc/nginx/nginx.conf
    #   ports:
    #     - "80:80"
    #   depends_on:
    #     - service1

    # volumes:
    #   mongo_data:
