version: '3'
services:
  service1:
    build: ./service1
    container_name: clasp_mobile
    restart: always
    # ports:
    #   - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./service1/.env
    environment:
      - MONGO_URI=mongodb://host.docker.internal:27017
      # - MONGO_URI=mongodb://mongo:27017
      # - MONGO_DB_NAME=claspMobileDB
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # depends_on:
    #   - mongo

    # mongo:
    #   image: mongo
    #   restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: username
    #   MONGO_INITDB_ROOT_PASSWORD: password
    # volumes:
    #   - mongo_data:/data/db
    # ports:
    #   - "27017:27017"

  nginx:
    image: nginx
    container_name: nginx_container
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/clasplabiml.xyz/fullchain.pem:/etc/nginx/cert.pem:ro
      - /etc/letsencrypt/live/clasplabiml.xyz/privkey.pem:/etc/nginx/key.pem:ro
    depends_on:
      - service1
    # volumes:
    #   mongo_data:
